"""initial schema

Revision ID: 1487cee03966
Revises: 
Create Date: 2025-09-26 11:57:51.502473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1487cee03966'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resguardantes',
    sa.Column('trabajador_id', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('trabajador_id')
    )
    op.create_index(op.f('ix_resguardantes_trabajador_id'), 'resguardantes', ['trabajador_id'], unique=False)
    op.create_table('ubicaciones',
    sa.Column('salon_id', sa.String(length=20), nullable=False),
    sa.Column('edificio', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('salon_id')
    )
    op.create_index(op.f('ix_ubicaciones_salon_id'), 'ubicaciones', ['salon_id'], unique=False)
    op.create_table('activos',
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('reguardo_id', sa.Integer(), nullable=False),
    sa.Column('no_serie', sa.Integer(), nullable=True),
    sa.Column('trabajador_id', sa.Integer(), nullable=False),
    sa.Column('descripcion_articulo', sa.String(length=100), nullable=True),
    sa.Column('caracteristicas', sa.String(length=100), nullable=True),
    sa.Column('salon_id', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['salon_id'], ['ubicaciones.salon_id'], ),
    sa.ForeignKeyConstraint(['trabajador_id'], ['resguardantes.trabajador_id'], ),
    sa.PrimaryKeyConstraint('equipo_id')
    )
    op.create_index(op.f('ix_activos_equipo_id'), 'activos', ['equipo_id'], unique=False)
    op.create_table('reportes',
    sa.Column('reporte_id', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipo_id'], ['activos.equipo_id'], ),
    sa.PrimaryKeyConstraint('reporte_id')
    )
    op.create_index(op.f('ix_reportes_reporte_id'), 'reportes', ['reporte_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reportes_reporte_id'), table_name='reportes')
    op.drop_table('reportes')
    op.drop_index(op.f('ix_activos_equipo_id'), table_name='activos')
    op.drop_table('activos')
    op.drop_index(op.f('ix_ubicaciones_salon_id'), table_name='ubicaciones')
    op.drop_table('ubicaciones')
    op.drop_index(op.f('ix_resguardantes_trabajador_id'), table_name='resguardantes')
    op.drop_table('resguardantes')
    # ### end Alembic commands ###
