"""Initial schema

Revision ID: e5c5e53eb703
Revises: 
Create Date: 2025-06-09 13:55:29.486285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5c5e53eb703'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resguardantes',
    sa.Column('clave', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('clave')
    )
    op.create_table('activos',
    sa.Column('id_activo', sa.Integer(), nullable=False),
    sa.Column('folio_resguardo', sa.Integer(), nullable=False),
    sa.Column('clave_activo', sa.Integer(), nullable=True),
    sa.Column('num_serie', sa.Integer(), nullable=True),
    sa.Column('clave_resguardante', sa.Integer(), nullable=False),
    sa.Column('caracteristicas', sa.String(length=100), nullable=True),
    sa.Column('factura', sa.String(length=100), nullable=True),
    sa.Column('ubicacion', sa.String(length=100), nullable=True),
    sa.Column('condiciones', sa.String(length=100), nullable=True),
    sa.Column('estatus', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['clave_resguardante'], ['resguardantes.clave'], ),
    sa.PrimaryKeyConstraint('id_activo')
    )
    op.create_table('reportes',
    sa.Column('id_reporte', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.Column('id_activo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_activo'], ['activos.id_activo'], ),
    sa.PrimaryKeyConstraint('id_reporte')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reportes')
    op.drop_table('activos')
    op.drop_table('resguardantes')
    # ### end Alembic commands ###
